import { sql } from "drizzle-orm";
import { boolean, check, doublePrecision, index, integer, jsonb, pgEnum, pgTable, text, timestamp, unique, uuid } from "drizzle-orm/pg-core";
import { DEFAULT_REGISTRATION_MODE, REGISTRATION_MODES } from "../instance/registration";
import { defaultLocale, type Locale } from "../locale/resolve-locale";
import { QUESTION_TYPES } from "../questions/question";
import { EMPTY_RICH_TEXT, type RichText } from "../rich-text/rich-text";
import { RSVP_STATUSES } from "../rsvps/form";
import { DEFAULT_GUEST_LIST_VISIBILITY, GUEST_LIST_VISIBILITIES } from "../rsvps/visibility";
import type { Theme } from "../themes/theme";

// Every table uses a UUIDv7 primary key generated by Postgres 18 (ADR-0004).
const id = () => uuid("id").primaryKey().default(sql`uuidv7()`);

const timestamps = {
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
};

// Hosts are Better Auth users (spec, "Identity and access"). Better Auth owns these four
// tables and their field names; a host's display name is the `name` field. Only the ids
// differ from Better Auth's defaults: Postgres generates them (ADR-0004).
export const user = pgTable("user", {
  id: id(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").notNull().default(false),
  image: text("image"),
  ...timestamps,
});

export const session = pgTable(
  "session",
  {
    id: id(),
    userId: uuid("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    token: text("token").notNull().unique(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    ...timestamps,
  },
  (table) => [index("session_user_id_idx").on(table.userId)],
);

export const account = pgTable(
  "account",
  {
    id: id(),
    userId: uuid("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    providerId: text("provider_id").notNull(),
    accountId: text("account_id").notNull(),
    password: text("password"),
    accessToken: text("access_token"),
    refreshToken: text("refresh_token"),
    idToken: text("id_token"),
    accessTokenExpiresAt: timestamp("access_token_expires_at", { withTimezone: true }),
    refreshTokenExpiresAt: timestamp("refresh_token_expires_at", { withTimezone: true }),
    scope: text("scope"),
    ...timestamps,
  },
  (table) => [index("account_user_id_idx").on(table.userId)],
);

export const verification = pgTable(
  "verification",
  {
    id: id(),
    identifier: text("identifier").notNull(),
    value: text("value").notNull(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    ...timestamps,
  },
  (table) => [index("verification_identifier_idx").on(table.identifier)],
);

export const registrationMode = pgEnum("registration_mode", REGISTRATION_MODES);

// The instance's own settings, which its operator edits on the instance settings page (spec,
// "Operator configuration"). Exactly one row, always: its key can only be true. The operator is
// held here rather than as a flag on each host, so two operators cannot exist.
export const instanceSettings = pgTable(
  "instance_settings",
  {
    id: boolean("id").primaryKey().default(true),
    registrationMode: registrationMode("registration_mode").notNull().default(DEFAULT_REGISTRATION_MODE),
    // Nobody once the operator deletes their account; OPERATOR_EMAIL names the next one.
    operatorId: uuid("operator_id").references(() => user.id, { onDelete: "set null" }),
    // The email of a sign-up that found the instance empty, from the moment it is let in until its
    // account exists and becomes the operator. Two first sign-ups at once cannot both hold it.
    firstAccountEmail: text("first_account_email"),
  },
  (table) => [check("instance_settings_one_row", sql`${table.id}`)],
);

// A host invitation (CONTEXT.md): the operator's permission for one person to become a host,
// carried by a single-use link. Only the hash of the link's token is kept, so a copy of the
// database hands out no invitations; the operator sees the link once, when it is made.
export const hostInvitation = pgTable("host_invitation", {
  id: id(),
  tokenHash: text("token_hash").notNull().unique(),
  // Who it is for, when the operator said: it fills in the sign-up form and restricts nothing.
  email: text("email"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
  usedAt: timestamp("used_at", { withTimezone: true }),
  // The email of the account that was created with it.
  usedByEmail: text("used_by_email"),
  revokedAt: timestamp("revoked_at", { withTimezone: true }),
});

export const eventState = pgEnum("event_state", ["draft", "published", "cancelled"]);

export const guestListVisibility = pgEnum("guest_list_visibility", GUEST_LIST_VISIBILITIES);

// An event belongs to one host. Its time is an instant plus the event's own IANA zone; all-day
// events store midnight in that zone with the flag set. The slug is the event link (ADR-0004).
// The theme is stored whole as JSON; parseTheme fills in whatever a row lacks, so an empty
// object is a complete default.
export const event = pgTable(
  "event",
  {
    id: id(),
    hostId: uuid("host_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    slug: text("slug").notNull().unique(),
    state: eventState("state").notNull().default("draft"),
    title: text("title").notNull(),
    startsAt: timestamp("starts_at", { withTimezone: true }).notNull(),
    endsAt: timestamp("ends_at", { withTimezone: true }),
    allDay: boolean("all_day").notNull().default(false),
    timeZone: text("time_zone").notNull(),
    location: text("location").notNull().default(""),
    // The description twice over: the document the host wrote, and the plain words derived from
    // it for the calendar file and the preview card.
    description: text("description").notNull().default(""),
    descriptionRich: jsonb("description_rich").$type<RichText>().notNull().default(EMPTY_RICH_TEXT),
    theme: jsonb("theme").$type<Theme>().notNull().default(sql`'{}'::jsonb`),
    // What the host asks of guests on the RSVP form (spec, "Per-event settings").
    plusOnesAllowed: integer("plus_ones_allowed").notNull().default(1),
    requirePlusOneNames: boolean("require_plus_one_names").notNull().default(false),
    askEmail: boolean("ask_email").notNull().default(false),
    guestListVisibility: guestListVisibility("guest_list_visibility").notNull().default(DEFAULT_GUEST_LIST_VISIBILITY),
    // Whether every host is emailed when a guest replies, changes their status, or removes their
    // RSVP (spec, "Host notifications"). On for new events; events from before 0.3 start with it
    // off, so an upgrade sends nobody mail they did not ask for (spec, story 141).
    notifyOnRsvp: boolean("notify_on_rsvp").notNull().default(true),
    // The language the host last saved the event form in, which mail about the event to its hosts
    // is written in: the request that queues such mail is usually a guest's, in their language.
    locale: text("locale").$type<Locale>().notNull().default(defaultLocale),
    ...timestamps,
  },
  (table) => [index("event_host_id_idx").on(table.hostId)],
);

export const rsvpStatus = pgEnum("rsvp_status", RSVP_STATUSES);

// One guest's answer to one event. Guests have no accounts: the edit token, stored hashed, is
// the only thing that proves an RSVP is yours, and it reaches the guest as an edit link and as a
// cookie on the device they answered from. Answering again replaces the RSVP the token names, so
// `repliedAt` is when they first replied and `updatedAt` when they last changed their mind. Two
// guests with the same name are two RSVPs (CONTEXT.md, "RSVP").
export const rsvp = pgTable(
  "rsvp",
  {
    id: id(),
    eventId: uuid("event_id")
      .notNull()
      .references(() => event.id, { onDelete: "cascade" }),
    status: rsvpStatus("status").notNull(),
    name: text("name").notNull(),
    plusOnes: integer("plus_ones").notNull().default(0),
    // As many entries as there are plus-ones; an entry is empty when the host does not ask for names.
    plusOneNames: text("plus_one_names").array().notNull().default(sql`'{}'::text[]`),
    email: text("email"),
    editTokenHash: text("edit_token_hash").notNull().unique(),
    // The secret in the stop link at the foot of every email to the guest (spec, "Guest mail"). In
    // clear, unlike the edit token: their mail is written long after their request is over, and
    // the link can only blank the email. Made the first time the RSVP has an email, then kept; an
    // RSVP that had an email before mail tokens existed got 32 hex digits instead (migration 0015).
    mailToken: text("mail_token").unique(),
    // The language the guest last saved their RSVP in, which their mail is written in.
    locale: text("locale").$type<Locale>().notNull().default(defaultLocale),
    repliedAt: timestamp("replied_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [index("rsvp_event_id_idx").on(table.eventId)],
);

export const questionType = pgEnum("question_type", QUESTION_TYPES);

// A prompt the host adds to an event, answered while a guest responds. Ordered by `position`,
// which is where the host put it in the editor. Only a choice question carries options.
export const question = pgTable(
  "question",
  {
    id: id(),
    eventId: uuid("event_id")
      .notNull()
      .references(() => event.id, { onDelete: "cascade" }),
    position: integer("position").notNull(),
    type: questionType("type").notNull(),
    prompt: text("prompt").notNull(),
    options: text("options").array().notNull().default(sql`'{}'::text[]`),
    required: boolean("required").notNull().default(false),
  },
  (table) => [index("question_event_id_idx").on(table.eventId)],
);

// One guest's answer to one question, belonging to their RSVP and visible only to the host.
// Removing the question takes its answers with it, as does removing the RSVP.
export const answer = pgTable(
  "answer",
  {
    id: id(),
    rsvpId: uuid("rsvp_id")
      .notNull()
      .references(() => rsvp.id, { onDelete: "cascade" }),
    questionId: uuid("question_id")
      .notNull()
      .references(() => question.id, { onDelete: "cascade" }),
    value: text("value").notNull(),
  },
  (table) => [index("answer_rsvp_id_idx").on(table.rsvpId), unique("answer_rsvp_question_unique").on(table.rsvpId, table.questionId)],
);

// A link a host has reset. The old slug is kept so that whoever still has it is told the link
// is no longer valid, rather than being shown a page that looks like a mistake (ADR-0004).
export const retiredSlug = pgTable(
  "retired_slug",
  {
    id: id(),
    slug: text("slug").notNull().unique(),
    eventId: uuid("event_id")
      .notNull()
      .references(() => event.id, { onDelete: "cascade" }),
    retiredAt: timestamp("retired_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [index("retired_slug_event_id_idx").on(table.eventId)],
);

// A host's own picture for an event, shown as its background or as the poster. An event has at
// most one: uploading again replaces it. The picture itself is kept in storage (ADR-0003), in the sizes
// uploads/renditions.ts names; what the server sampled from it for the theme is kept here
// (uploads/sample.ts). Deleting the event takes the row with it, and whatever deletes the event
// removes the files (events/repository.ts).
export const upload = pgTable("upload", {
  id: id(),
  eventId: uuid("event_id")
    .notNull()
    .unique()
    .references(() => event.id, { onDelete: "cascade" }),
  // What the picture shows, for guests who use a screen reader. Empty when it is decoration.
  altText: text("alt_text").notNull().default(""),
  // Its average luminance (0 dark to 1 light), its accent (#rrggbb), and its brightest and
  // darkest points as the glass sees them (#rrggbb).
  luminance: doublePrecision("luminance").notNull(),
  accent: text("accent").notNull(),
  lightest: text("lightest").notNull(),
  darkest: text("darkest").notNull(),
  // As the poster: the brightest and darkest points of its blurred copy behind it (#rrggbb), and
  // the poster rendition's size in pixels, so the page gives it its place before it arrives.
  posterLightest: text("poster_lightest").notNull(),
  posterDarkest: text("poster_darkest").notNull(),
  posterWidth: integer("poster_width").notNull(),
  posterHeight: integer("poster_height").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

// Every email about an event, to a guest or to a host, waits here until the mail worker sends it
// (mail/outbox.ts; spec, "Mail outbox and worker"). A message that sent is deleted; one that failed
// keeps how often it has, why it last did, and when to try again. Deleting the event takes its
// unsent mail with it.
export const mailOutbox = pgTable(
  "mail_outbox",
  {
    id: id(),
    eventId: uuid("event_id").references(() => event.id, { onDelete: "cascade" }),
    to: text("to").notNull(),
    subject: text("subject").notNull(),
    text: text("text").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    sendAfter: timestamp("send_after", { withTimezone: true }).notNull().defaultNow(),
    attempts: integer("attempts").notNull().default(0),
    lastError: text("last_error"),
  },
  (table) => [index("mail_outbox_event_id_idx").on(table.eventId)],
);
