import { sql } from "drizzle-orm";
import { boolean, index, integer, jsonb, pgEnum, pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";
import { RSVP_STATUSES } from "../rsvps/form";
import { DEFAULT_GUEST_LIST_VISIBILITY, GUEST_LIST_VISIBILITIES } from "../rsvps/visibility";
import type { Theme } from "../themes/theme";

// Every table uses a UUIDv7 primary key generated by Postgres 18 (ADR-0004).
const id = () => uuid("id").primaryKey().default(sql`uuidv7()`);

const timestamps = {
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
};

// Hosts are Better Auth users (spec, "Identity and access"). Better Auth owns these four
// tables and their field names; a host's display name is the `name` field. Only the ids
// differ from Better Auth's defaults: Postgres generates them (ADR-0004).
export const user = pgTable("user", {
  id: id(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").notNull().default(false),
  image: text("image"),
  ...timestamps,
});

export const session = pgTable(
  "session",
  {
    id: id(),
    userId: uuid("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    token: text("token").notNull().unique(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    ...timestamps,
  },
  (table) => [index("session_user_id_idx").on(table.userId)],
);

export const account = pgTable(
  "account",
  {
    id: id(),
    userId: uuid("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    providerId: text("provider_id").notNull(),
    accountId: text("account_id").notNull(),
    password: text("password"),
    accessToken: text("access_token"),
    refreshToken: text("refresh_token"),
    idToken: text("id_token"),
    accessTokenExpiresAt: timestamp("access_token_expires_at", { withTimezone: true }),
    refreshTokenExpiresAt: timestamp("refresh_token_expires_at", { withTimezone: true }),
    scope: text("scope"),
    ...timestamps,
  },
  (table) => [index("account_user_id_idx").on(table.userId)],
);

export const verification = pgTable(
  "verification",
  {
    id: id(),
    identifier: text("identifier").notNull(),
    value: text("value").notNull(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    ...timestamps,
  },
  (table) => [index("verification_identifier_idx").on(table.identifier)],
);

export const eventState = pgEnum("event_state", ["draft", "published"]);

export const guestListVisibility = pgEnum("guest_list_visibility", GUEST_LIST_VISIBILITIES);

// An event belongs to one host. Its time is an instant plus the event's own IANA zone; all-day
// events store midnight in that zone with the flag set. The slug is the event link (ADR-0004).
// The theme is stored whole as JSON; parseTheme fills in whatever a row lacks, so an empty
// object is a complete default.
export const event = pgTable(
  "event",
  {
    id: id(),
    hostId: uuid("host_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    slug: text("slug").notNull().unique(),
    state: eventState("state").notNull().default("draft"),
    title: text("title").notNull(),
    startsAt: timestamp("starts_at", { withTimezone: true }).notNull(),
    endsAt: timestamp("ends_at", { withTimezone: true }),
    allDay: boolean("all_day").notNull().default(false),
    timeZone: text("time_zone").notNull(),
    location: text("location").notNull().default(""),
    description: text("description").notNull().default(""),
    theme: jsonb("theme").$type<Theme>().notNull().default(sql`'{}'::jsonb`),
    // What the host asks of guests on the RSVP form (spec, "Per-event settings").
    plusOnesAllowed: integer("plus_ones_allowed").notNull().default(1),
    requirePlusOneNames: boolean("require_plus_one_names").notNull().default(false),
    askEmail: boolean("ask_email").notNull().default(false),
    guestListVisibility: guestListVisibility("guest_list_visibility").notNull().default(DEFAULT_GUEST_LIST_VISIBILITY),
    ...timestamps,
  },
  (table) => [index("event_host_id_idx").on(table.hostId)],
);

export const rsvpStatus = pgEnum("rsvp_status", RSVP_STATUSES);

// One guest's answer to one event. Guests have no accounts: the edit token, stored hashed, is
// the only thing that proves an RSVP is yours, and it reaches the guest as an edit link and as a
// cookie on the device they answered from. Answering again replaces the RSVP the token names, so
// `repliedAt` is when they first replied and `updatedAt` when they last changed their mind. Two
// guests with the same name are two RSVPs (CONTEXT.md, "RSVP").
export const rsvp = pgTable(
  "rsvp",
  {
    id: id(),
    eventId: uuid("event_id")
      .notNull()
      .references(() => event.id, { onDelete: "cascade" }),
    status: rsvpStatus("status").notNull(),
    name: text("name").notNull(),
    plusOnes: integer("plus_ones").notNull().default(0),
    // As many entries as there are plus-ones; an entry is empty when the host does not ask for names.
    plusOneNames: text("plus_one_names").array().notNull().default(sql`'{}'::text[]`),
    email: text("email"),
    editTokenHash: text("edit_token_hash").notNull().unique(),
    repliedAt: timestamp("replied_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [index("rsvp_event_id_idx").on(table.eventId)],
);
